movies = []
print('List of movies:')
print(movies)
print('Add movie "Home alone":')
movies.append('Home alone')
print('Len of movies: ', len(movies))
print('Add movie "X-man" at fist position')
movies.insert(0, "X-man")
print(movies)
print('Add two movies in the end')
movies.append('Spiderman')
movies.append('Batman')
print(movies)
print('Len of moovies: ', len(movies))
print('Remove "Home alone" by name')
movies.remove('Home alone')
print(movies)
print('Delete "Spiderman" by position')
del movies[1]
print(movies)
print('Add two films by insert')
movies.insert(1, 'Anaconda')
movies.insert(0, 'Breakeng bad')
print(movies)
print('Sorted movies: ', sorted(movies))
print('Sorted movies reverse: ', sorted(movies, reverse=True))
movies.reverse()
print('Reverse original list: ', movies)
movies.reverse()
print('Reverse original list back: ', movies)
movies.sort()
print('Sort movies: ', movies)
movies.sort(reverse=True)
print('Sort reverse movies: ', movies)
print('Len of movies:', len(movies))
print('First:', movies[0])
print('Second:', movies[1])
print('Third:', movies[2])
print('Fourth:', movies[3])
