countries = ['Ukraine', 'Belarus', 'Turkey', 'Egypt', 'Russia']
print('Normal: ', countries)
print('Sorted: ', sorted(countries))
print('Normal:', countries)
print('Sorted reversed: ', sorted(countries, reverse=True))
print('Normal: ', countries)
countries.reverse()
print('Reverse: ', countries)
countries.reverse()
print('Normal: ', countries)
countries.sort()
print('Sort: ', countries)
countries.sort(reverse=True)
print('Reversed Sort: ', countries)
